import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import ttest_ind

# Снимаем ограничение на количество столбцов
pd.set_option('display.max_columns', 25)
# Увеличиваем общую ширину вывода (чтобы столбцы не переносились на новую строку)
pd.set_option('display.width', 200)
# Снимает ограничение на ширину каждого столбца
pd.set_option("display.max_colwidth", None)

# Возврат:
# pd.set_option('display.max_rows', None)
# pd.reset_option('display.max_rows')
# pd.reset_option("display.max_colwidth")

#
# ----------------------- ASSIGNMENT 3_4 ----------------------
#

import warnings
warnings.filterwarnings("ignore")

import os
import matplotlib.pyplot as plt

np.random.seed(0)   # Do not change this value: required to be compatible with solutions generated by the autograder.

# -------------------------------------------------------------

def engagement_model():

    train = pd.read_csv('assets/train.csv')
    test = pd.read_csv('assets/test.csv')

    print(train)
    print(test)

    # Features list from the task
    features = [
        'title_word_count',
        'document_entropy',
        'freshness',
        'easiness',
        'fraction_stopword_presence',
        'speaker_speed',
        'silent_period_rate'
    ]

    # Cutting the data for Training
    X_train = train[features]

    # Cutting the data for Labels
    y_train = train['engagement']

    print('X_train, y_train:')
    print(X_train)
    print(y_train)

    # Cutting the data for Test
    X_test = test[features]

    print('X_test:')
    print(X_test)

    rec = test['id']

    print('rec')
    print(rec)

    from sklearn.ensemble import GradientBoostingClassifier

    clf = GradientBoostingClassifier().fit(X_train, y_train)
    y_test = clf.predict_proba(X_test)[:, 1]

    print('y_test:')
    print(y_test)

    rec = pd.Series(y_test, index=rec.values, name='engagement', dtype='float32')
    rec.index.name = 'id'

    print('rec:')
    print(rec)
    print(type(rec))

    from sklearn.model_selection import cross_val_score
    from sklearn.linear_model import LogisticRegression
    from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

    # Checking "out-of-the-box" models for cross-validations roc_auc
    for model in [LogisticRegression(max_iter=1000), RandomForestClassifier(), GradientBoostingClassifier()]:
        scores = cross_val_score(model, X_train, y_train, cv=5, scoring='roc_auc')
        print(f"{model.__class__.__name__}: AUC = {scores.mean():.4f}")


    # ------------- Оцениваем степерь важности признаков -------------

    # Получаем веса важности от модели
    importances = clf.feature_importances_

    # Создаем красивую таблицу для вывода
    feature_importance_df = pd.DataFrame({
        'Признак': features,
        'Важность (%)': importances * 100
    }).sort_values(by='Важность (%)', ascending=False)  # Сортируем по убыванию

    print("\n=== РЕЙТИНГ ВАЖНОСТИ ПРИЗНАКОВ ===")
    print(feature_importance_df.to_string(index=False))

    #
    # Вот готовый код, который построит графики AUC (ROC-кривые)
    # для Gradient Boosting на кросс-валидации:
    #
    import matplotlib.pyplot as plt
    from sklearn.model_selection import KFold
    from sklearn.metrics import roc_curve, auc

    # Настраиваем разбиение на 5 частей (фолдов)
    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    plt.figure(figsize=(8, 6))

    # Считаем и рисуем кривую для каждого фолда
    for fold, (train_idx, val_idx) in enumerate(kf.split(X_train)):
        # Делим X_train и y_train на текущие обучающую и валидационную части
        X_tr, X_val = X_train.iloc[train_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train.iloc[train_idx], y_train.iloc[val_idx]

        # Обучаем модель на текущем фолде
        model = GradientBoostingClassifier(random_state=42).fit(X_tr, y_tr)

        # Предсказываем вероятности для валидационной части
        probs = model.predict_proba(X_val)[:, 1]

        # Считаем точки для графика и AUC
        fpr, tpr, _ = roc_curve(y_val, probs)
        roc_auc = auc(fpr, tpr)

        # Рисуем линию для текущего фолда
        plt.plot(fpr, tpr, lw=1.5, label=f'Fold {fold + 1} (AUC = {roc_auc:.4f})')

    # Рисуем линию случайного угадывания (диагональ)
    plt.plot([0, 1], [0, 1], color='red', lw=2, linestyle='--', label='Random Guess (AUC = 0.5)')

    # Настройки графика
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate (Доля ложных ответов)')
    plt.ylabel('True Positive Rate (Доля верных ответов)')
    plt.title('ROC-кривые на 5-фолдовой кросс-валидации (GBDT)')
    plt.legend(loc="lower right")
    plt.grid(True)

    # Показываем график
    plt.show()

    return rec


# -------------------------------------------------------------

stu_ans = engagement_model()

# assert isinstance(stu_ans, pd.Series), "Your function should return a pd.Series. "
# assert len(stu_ans) == 2309, "Your series is of incorrect length: expected 2309 "
# assert np.issubdtype(stu_ans.index.dtype, np.integer), "Your answer pd.Series should have an index of integer type representing video id."


#
# -------------------------------------------------------------------------------------
# ASSIGNMENT 4 - Predicting and understanding viewer engagement with educational videos
# -------------------------------------------------------------------------------------
#
# With the accelerating popularity of online educational experiences, the role of online lectures
# and other educational video continues to increase in scope and importance. Open access educational
# repositories such as videolectures.net, as well as Massive Open Online Courses (MOOCs)
# on platforms like Coursera, have made access to many thousands of lectures and tutorials
# an accessible option for millions of people around the world. Yet this impressive volume
# of content has also led to a challenge in how to find, filter, and match these videos with learners.
# This assignment gives you an example of how machine learning can be used to address part of that challenge.
#
# About the prediction problem
#
# One critical property of a video is engagement: how interesting or "engaging" it is for viewers,
# so that they decide to keep watching. Engagement is critical for learning, whether the instruction
# is coming from a video or any other source. There are many ways to define engagement with video,
# but one common approach is to estimate it by measuring how much of the video a user watches.
# If the video is not interesting and does not engage a viewer, they will typically abandon it quickly,
# e.g. only watch 5 or 10% of the total.
#
# A first step towards providing the best-matching educational content is to understand which features
# of educational material make it engaging for learners in general. This is where predictive modeling
# can be applied, via supervised machine learning. For this assignment, your task is to predict how
# engaging an educational video is likely to be for viewers, based on a set of features extracted from
# the video's transcript, audio track, hosting site, and other sources.
#
# We chose this prediction problem for several reasons:
#
# It combines a variety of features derived from a rich set of resources connected to the original data;
# The manageable dataset size means the dataset and supervised models for it can be easily explored
# on a wide variety of computing platforms;
# Predicting popularity or engagement for a media item, especially combined with understanding which
# features contribute to its success with viewers, is a fun problem but also a practical representative
# application of machine learning in a number of business and educational sectors.
#
# About the dataset
# We extracted training and test datasets of educational video features from the VLE Dataset put together
# by researcher Sahan Bulathwela at University College London.
#
# We provide you with two data files for use in training and validating your models: train.csv and test.csv.
# Each row in these two files corresponds to a single educational video, and includes information
# about diverse properties of the video content as described further below. The target variable
# is engagement which was defined as True if the median percentage of the video watched across
# all viewers was at least 30%, and False otherwise.
#
# Note: Any extra variables that may be included in the training set are simply for your interest
# if you want an additional source of data for visualization, or to enable unsupervised
# and semi-supervised approaches. However, they are not included in the test set and thus
# cannot be used for prediction. Only the data already included in your Coursera directory
# can be used for training the model for this assignment.
#
# For this final assignment, you will bring together what you've learned across all four weeks of this course,
# by exploring different prediction models for this new dataset. In addition, we encourage you to apply
# what you've learned about model selection to do hyperparameter tuning using training/validation splits
# of the training data, to optimize the model and further increase its performance. In addition
# to a basic evaluation of model accuracy, we've also provided a utility function to visualize
# which features are most and least contributing to the overall model performance.
#
# File descriptions:
# assets/train.csv - the training set (Use only this data for training your model!)
# assets/test.csv - the test set
#
# Data fields
#
# train.csv & test.csv:
#
# title_word_count - the number of words in the title of the video.
#
# document_entropy - a score indicating how varied the topics are covered in the video, based on the transcript.
# Videos with smaller entropy scores will tend to be more cohesive and more focused on a single topic.
#
# freshness - The number of days elapsed between 01/01/1970 and the lecture published date. Videos that
# are more recent will have higher freshness values.
#
# easiness - A text difficulty measure applied to the transcript.
# A lower score indicates more complex language used by the presenter.
#
# fraction_stopword_presence - A stopword is a very common word like 'the' or 'and'.
# This feature computes the fraction of all words that are stopwords in the video lecture transcript.
#
# speaker_speed - The average speaking rate in words per minute of the presenter in the video.
#
# silent_period_rate - The fraction of time in the lecture video that is silence (no speaking).
# train.csv only:
#
# engagement - Target label for training. True if learners watched a substantial
# portion of the video (see description), or False otherwise.
#
# Evaluation
# Your predictions will be given as the probability that the corresponding video will be engaging to learners.
#
# The evaluation metric for this assignment is the Area Under the ROC Curve (AUC).
#
# Your grade will be based on the AUC score computed for your classifier.
# A model with an AUC (area under ROC curve) of at least 0.8 passes this assignment,
# and over 0.85 will receive full points.
#
# For this assignment, create a function that trains a model to predict significant learner engagement
# with a video using asset/train.csv. Using this model, return a Pandas Series object
# of length 2309 with the data being the probability that each corresponding video from
# readonly/test.csv will be engaging (according to a model learned from the 'engagement' label
# in the training set), and the video index being in the id field.
#
# Example:
#
# id
#    9240    0.401958
#    9241    0.105928
#    9242    0.018572
#              ...
#    9243    0.208567
#    9244    0.818759
#    9245    0.018528
#          ...
#    Name: engagement, dtype: float32
#
# Hints
# Make sure your code is working before submitting it to the autograder.
#
# Print out and check your result to see whether there is anything weird (e.g., all probabilities are the same).
#
# Generally the total runtime should be less than 10 mins.
#
# Try to avoid global variables. If you have other functions besides engagement_model,
# you should move those functions inside the scope of engagement_model.
#
# Be sure to first check the pinned threads in Week 4's discussion forum
# if you run into a problem you can't figure out.
#
# Extensions
# If this prediction task motivates you to explore further, you can find more details here
# on the original VLE dataset and others related to video engagement: https://github.com/sahanbull/VLE-Dataset
#









