name: Run Python Script

on:
  workflow_dispatch: # Это создает кнопку ручного запуска

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Скачиваем код из main
        uses: actions/checkout@v4

      - name: Настраиваем Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Устанавливаем библиотеки (если нужны)
        run: |
          pip install pandas  # Добавьте сюда другие библиотеки через пробел, если используете их

      - name: Запуск скрипта
        run: python "20260824 Assignment 4_3.py" # Замените script.py на имя вашего файла
